// Generated by Selenium IDE

//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
package ru.stqa.pft.sandbox.tests;

import org.testng.annotations.*;

public class AuthorizationTest extends TestBase {

    @Test
    public void testLogin() {
        app.getAuthorizationHelper().setLogin("jowig50885@isecv.com");
        app.getAuthorizationHelper().setPassword("z119f0a5A");
        app.getAuthorizationHelper().loginButtonClick();
    }

}
